cauth/urls.py
from django.urls import path

from cauth import views

# Give namespace to the app
# so that login view can be called within
# navbar using app_name:view_name
app_name = "cauth"

urlpatterns = [
    path("login/", views.login_user, name = "login"),
    path("logout/", views.logout_user, name = "logout"),
    path("register/", views.register, name = "register"),
]

htmx_urlpatterns = [
    path("check_username/", views.check_username, name = "check_username"),
]

urlpatterns += htmx_urlpatterns

main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path("", views.index, name="home"),
    path("article/<int:pk>", views.article_details, name="article_details"),
    path("tag/<int:pk>", views.tag_list, name="tag_list"),
    path("publish", views.create_article, name="create_article"),
    path("delete_article/<int:pk>", views.delete_article, name="delete_article"),
    path("edit_article/<int:pk>", views.edit_article, name="edit_article"),
    path("article_archive/<int:year>/<int:month>", views.article_archive, name="article_archive"),
    path("profile/<int:pk>", views.get_profile, name="profile"),
    path("edit_profile/<int:pk>", views.edit_profile, name="edit_profile"),
]

htmx_urlpatterns = [
    path("like_article/<int:pk>", views.like_article, name = "like_article"),
]

urlpatterns += htmx_urlpatterns

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include("main.urls")),
    path("auth/", include("cauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors" />
    <meta name="generator" content="Hugo 0.104.2" />
    <title>Creo - Articles for everyone</title>
    <link rel="icon" href="{% static 'favicon.ico' %}" />
    <link rel="icon" href="static/favicon.ico" />

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.2/assets/img/favicons/apple-touch-icon.png" sizes="180x180" />
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png" />
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png" />
    <link rel="manifest" href="/docs/5.2/assets/img/favicons/manifest.json" />
    <link rel="mask-icon" href="/docs/5.2/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9" />
    <link rel="icon" href="/docs/5.2/assets/img/favicons/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400&display=swap" rel="stylesheet" />

    <script src="https://kit.fontawesome.com/6d805d00dd.js" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href={% static 'styles.css' %} />
    <script src="script.js"></script>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <!-- Htmx -->
    <script src="https://unpkg.com/htmx.org@1.8.4" integrity="sha384-wg5Y/JwF7VxGk4zLsJEcAojRtlVp1FKKdGy1qN+OMtdq72WRvX/EdRdqg/LOhYeV" crossorigin="anonymous"></script>

    {% block head %}{% endblock head %}
</head>

<body>

    {% include "navbar.html" %}

    {% block body %}{% endblock body %}

    <main class="container" style="min-height: 100vh">
        <div class="col">
            {% if messages %} {% for message in messages %}
            <div class="alert alert-{{ message.extra_tags }}">{{ message }}</div>
            {% endfor %} {% endif %}
        </div>

        {% block container %}{% endblock container %}

    </main>

    {% include "footer.html" %}

    {% block script %}{% endblock script %}

</body>

</html>

templates/footer.html
<footer class="blog-footer">
    <p>
        Website made by Praveen Kumar
    </p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

templates/navbar.html
<div class="container">
    <header class="blog-header lh-1 py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                <a class="link-secondary" href={% url 'create_article' %}>Publish</a>
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href={% url 'home' %}>Creo</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <span class="mx-2">
                    {% if user.is_authenticated %}
                        <div class="btn-group dropdown dropdown-center">
                            <button type="button"
                                    class="btn btn-danger dropdown-toggle"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                <span class="desktop-only">
                                    {{ user.username }}
                                </span>
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href={% url 'profile' user.pk %}>Profile</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider" />
                                </li>
                                <li>
                                    <a class="dropdown-item" href={% url 'cauth:logout' %}>Sign out</a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <a class="link-secondary text-decoration-none"
                           href="{% url 'cauth:login' %}">Sign In</a>
                    {% endif %}
                </span>
                <span class="mx-2">
                    {% if user.is_authenticated == False %}
                        <a class="btn btn-sm btn-danger rounded-pill"
                           href="{% url 'cauth:register' %}">Sign up</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </header>

    {% comment %} Tags navbar {% endcomment %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div></div>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100 justify-content-evenly">
                {% for tag in tags %}
                    <li class="nav-item">
                        <a class="nav-link link-secondary p-2" href={% url 'tag_list' tag.pk %}>{{ tag }}</a>
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    </nav>
</div>